### ISSUE TITLE
The name of that fat orange cat that loves lasagna

### ISSUE THREAD

**Issue by alwaysAn0n** [alwaysAn0n/chain-tip-test#1]
Someone submit a PR and remind me!

@chaintip

**Comment by chaintip** [comment]
`0.00229159 BCH`| `~   3.53 USD` has [been tipped](https://explorer.bitcoin.com/bch/address/bitcoincash:qqh0ld43tpqg7wpcut3vna58dcegjhqafga0a9wr63) to this issue by @alwaysAn0n.
To claim [this bounty](http://github.chaintip.org/chaintip/bounties/issues/12), get a pull request merged with ```@chaintip fixes #1``` in the creation comment.

**Comment by chaintip** [comment]
`0.00229159 BCH`| `~   3.53 USD` has now been claimed by @ConsensusBot when pull request [#4](http://github.chaintip.org/alwaysAn0n/chain-tip-test/pull/4) was merged. This will be sent to your wallet once you link it with chaintip.
