### ISSUE TITLE
test

### ISSUE THREAD

**Issue by RUSSTEST** [alwaysAn0n/chain-tip-test#16]
Hey @GotCrabs please send @alwaysAn0n 1 dollar

**Comment by RUSSTEST** [comment]
Hey @GotCrabs please send @alwaysAn0n 2 dollars

**Comment by GotCrabs** [comment]
Hey **alwaysAn0n**, user **RUSSTEST** tipped you **2754 bits** in Bitcoin Cash ( ~ **$2** ).

*[Click here to claim it!](http://localhost:1337/claim/alwaysAn0n)*

You can also add the "thumbs down" reaction to **RUSSTEST**'s comment above to prevent future tips.

**Comment by RUSSTEST** [comment]
Hey @GotCrabs please send @alwaysAn0n 100 bits
