### ISSUE TITLE
Purely peer-to-peer version of electronic cash

### ISSUE THREAD

**Issue by alwaysAn0n** [alwaysAn0n/chain-tip-test#2]
What's the name of this thing?  Someone help!

@chaintip

**Comment by chaintip** [comment]
`0.00229159 BCH`| `~   3.52 USD` has [been tipped](https://explorer.bitcoin.com/bch/address/bitcoincash:qqh0ld4rgf88gqsp8hsypfk980a54s00fcggee76vc) to this issue by @alwaysAn0n.
To claim [this bounty](http://github.chaintip.org/chaintip/bounties/issues/13), get a pull request merged with ```@chaintip fixes #2``` in the creation comment.

**Comment by tea-spoon** [comment]
Thanks for testing this out @alwaysAn0n @chaintip!

**Comment by chaintip** [comment]
@alwaysAn0n has [claimed](https://explorer.bitcoin.com/bch/address/bitcoincash:qqh0ld4z3vn9wpd9n60e53t7flc0alqvgvwty6xygw) the `0.0013468 BCH`| `~   2.00 USD` sent by @tea-spoon via [chaintip](http://www.chaintip.org).

**Comment by chaintip** [comment]
`0.00229159 BCH`| `~   3.41 USD` has now been claimed by @mesquka when pull request [#5](http://github.chaintip.org/alwaysAn0n/chain-tip-test/pull/5) was merged.
