### ISSUE TITLE
Actor in his underware, singing into a candlestick, weird scientology ...

### ISSUE THREAD

**Issue by alwaysAn0n** [alwaysAn0n/chain-tip-test#3]
What's his name?  Help!

@chaintip

**Comment by chaintip** [comment]
`0.00080533 BCH`| `~   1.24 USD` has [been tipped](https://explorer.bitcoin.com/bch/address/bitcoincash:qqh0ld4yglpgmg006yjgcj73t0rqtfxw7ch2qeupln) to this issue by @alwaysAn0n.
To claim [this bounty](http://github.chaintip.org/chaintip/bounties/issues/14), get a pull request merged with ```@chaintip fixes #3``` in the creation comment.

**Comment by chaintip** [comment]
`0.00080533 BCH`| `~   1.20 USD` has now been claimed by @mebeim when pull request [#9](http://github.chaintip.org/alwaysAn0n/chain-tip-test/pull/9) was merged.
